export const homePageAddress = '/'
export const playersNamesAndNumberPageAddress = 'players-names-and-number'
export const distributionOfRolesAddress = 'distribution-of-roles'
export const dayAddress = 'day'
export const nightAddress = 'night'